name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code
      uses: actions/checkout@v2
      with:
        path: ./src/github.com/${{ github.repository }}

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Setup build environment   
      run: |
        mkdir -p $GOCACHE
        cd ./src/github.com/${{ github.repository }}
        make build-deps
        go version

    - name: Test and build package
      run: |
        cd ./src/github.com/${{ github.repository }}
        make test
        make build

    - name: Check project
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.27
